# Generated by Django 5.1.4 on 2025-01-17 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_encryptedfile_is_shared_encryptedfile_shared_with_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encryptedfile',
            options={},
        ),
    ]
