# Generated by Django 5.1.4 on 2025-01-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_remove_fileshare_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedfile',
            name='shared_with',
        ),
    ]
